name: PyMC3-HMM

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  python-tests:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint code
      run: |
        pylint pymc3_hmm/ tests/
    - name: Check documentation style
      run: |
        pydocstyle pymc3_hmm/
    - name: Check format with black
      run: |
        black --check pymc3_hmm/ tests/
    - name: Test with pytest
      run: |
        pytest tests --cov=pymc3_hmm --cov-report=xml:./coverage.xml
    - name: Fetch main for coverage diff
      run: |
        git fetch --no-tags --prune origin main
    - name: Check coverage
      run: |
        diff-cover ./coverage.xml --compare-branch=origin/main --fail-under=100 --diff-range-notation '..'
